services:
  api:
    build: ./api
    container_name: django_api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    command: daphne config.asgi:application -b 0.0.0.0 -p 8000
volumes:
  postgres_data:
