# Generated by Django 5.2.6 on 2025-09-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomjoinlog',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AlterField(
            model_name='roomjoinlog',
            name='frequency',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
