name: Build and Push Docker Image to AWS ECR and Deploy to ECS + Trigger Netlify frontend Build

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for API changes
        id: api_changes
        run: |
          if git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep '^api/'; then
            echo "api_changed=true" >> $GITHUB_OUTPUT
          else
            echo "api_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Configure AWS credentials
        if: steps.api_changes.outputs.api_changed == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: steps.api_changes.outputs.api_changed == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        if: steps.api_changes.outputs.api_changed == 'true'
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest ./api

      - name: Push Docker image to ECR
        if: steps.api_changes.outputs.api_changed == 'true'
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to ECS
        if: steps.api_changes.outputs.api_changed == 'true'
        run: |
          aws ecs update-service \
            --cluster django-livekit-radio \
            --service django-livekit-radio-api-service \
            --force-new-deployment \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - name: Wait for ECS deployment
        if: steps.api_changes.outputs.api_changed == 'true'
        run: |
          aws ecs wait services-stable \
            --cluster django-livekit-radio \
            --services django-livekit-radio-api-service
      - name: Run migrations
        if: steps.api_changes.outputs.api_changed == 'true'
        run: |
          aws ecs run-task \
            --cluster django-livekit-radio \
            --launch-type FARGATE \
            --task-definition django-livekit-radio-api-task \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-066cffe0cda186a15,subnet-02a9c7d8bf8de7890],securityGroups=[sg-0c9cd59940ed73fe5],assignPublicIp=ENABLED}" \
            --overrides '{"containerOverrides":[{"name":"api","command":["python","manage.py","migrate","--noinput"]}]}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - name: Check for web changes
        id: web_changes
        run: |
          if git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep '^web/'; then
            echo "web_changed=true" >> $GITHUB_OUTPUT
          else
            echo "web_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Trigger Netlify build
        if: steps.web_changes.outputs.web_changed == 'true'
        run: curl -X POST -d '{}' "$NETLIFY_BUILD_HOOK_URL"
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
      - name: Publish latest Netlify deploy
        if: steps.web_changes.outputs.web_changed == 'true'
        run: |
          SITE_ID="89b82761-2f1c-4fc7-9b22-cc251a509274"
          DEPLOY_ID=$(curl -s -H "Authorization: Bearer $NETLIFY_ACCESS_TOKEN" \
            "https://api.netlify.com/api/v1/sites/$SITE_ID/deploys" | jq -r '.[0].id')
          echo "Latest deploy ID: $DEPLOY_ID"
          curl -X POST -H "Authorization: Bearer $NETLIFY_ACCESS_TOKEN" \
            "https://api.netlify.com/api/v1/sites/$SITE_ID/deploys/$DEPLOY_ID/restore"
        env:
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
